CREATE DATABASE TOKYO_2021 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE TOKYO_2021;

CREATE TABLE TB_ATHLETES(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 11085
name VARCHAR(80), -- 35
noc VARCHAR(60), -- 34
discipline VARCHAR(60) -- 21
);

CREATE TABLE TB_COACHES(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 394
name VARCHAR(80), -- 30
noc VARCHAR(60), -- 26
discipline VARCHAR(60), -- 17
event VARCHAR(25) -- 8
);

CREATE TABLE TB_ENTRIES_GENDER(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 46
discipline VARCHAR(60), -- 21
female SMALLINT,
male SMALLINT,
total SMALLINT
);

CREATE TABLE TB_MEDALS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ranking TINYINT,
team VARCHAR(80), -- 26
gold SMALLINT,
silver SMALLINT,
bronze SMALLINT,
total SMALLINT,
rank_by_total TINYINT
);

CREATE TABLE TB_TEAMS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 743
name VARCHAR(80), -- 34
discipline VARCHAR(60), -- 19
noc VARCHAR(80), -- 26
event VARCHAR(60) -- 32
);

