CREATE DATABASE TOKYO_2021 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
-- CREATE DATABASE TOKYO_2021 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_la_0900_ai_ci;
-- DROP DATABASE TOKYO_2021;

USE TOKYO_2021;

CREATE TABLE TB_ATLETAS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 11085
nome VARCHAR(80), -- 35
pais VARCHAR(60), -- 34
disciplina VARCHAR(60) -- 21
);

SELECT COUNT(*) FROM TB_ATLETAS; -- 11085
SELECT MAX(LENGTH(nome)) FROM TB_ATLETAS; -- 35
SELECT MIN(LENGTH(nome)) FROM TB_ATLETAS; -- 4
SELECT * FROM TB_ATLETAS ORDER BY LENGTH(nome) LIMIT 10;
SELECT * FROM TB_ATLETAS ORDER BY LENGTH(nome) DESC LIMIT 10;

SELECT MAX(LENGTH(nome)), MAX(LENGTH(pais)), MAX(LENGTH(disciplina)) FROM TB_ATLETAS;
-- 35, 34, 21 


CREATE TABLE TB_TECNICOS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 394
nome VARCHAR(100), -- 30
pais VARCHAR(60), -- 26
disciplina VARCHAR(60), -- 17
evento VARCHAR(25) -- 8
);

SELECT COUNT(*) FROM TB_TECNICOS;
SELECT MAX(LENGTH(nome)), MAX(LENGTH(pais)), MAX(LENGTH(disciplina)), MAX(LENGTH(evento)) FROM TB_TECNICOS;
-- 30, 26, 17, 8

CREATE TABLE TB_ENTRIES_GENDER(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 46
disciplina VARCHAR(60), -- 21
female SMALLINT,
male SMALLINT,
total SMALLINT
);

DROP TABLE TB_ENTRIES_GENDER;
SELECT * FROM TB_ENTRIES_GENDER;
SELECT COUNT(*) FROM TB_ENTRIES_GENDER;
SELECT MAX(LENGTH(disciplina)) FROM TB_ENTRIES_GENDER;

CREATE TABLE TB_MEDALS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ranking TINYINT,
team VARCHAR(80), -- 26
gold SMALLINT,
silver SMALLINT,
bronze SMALLINT,
total SMALLINT,
ranking_by_total TINYINT
);

SELECT * FROM TB_MEDALS;
SELECT MAX(LENGTH(team)) FROM TB_MEDALS; 

CREATE TABLE TB_TEAMS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 743
nome VARCHAR(80), -- 34
disciplina VARCHAR(60), -- 19
noc VARCHAR(80), -- 26
evento VARCHAR(60) -- 32
);

SELECT COUNT(*) FROM TB_TEAMS;
SELECT MAX(LENGTH(nome)), MAX(LENGTH(disciplina)), MAX(LENGTH(noc)), MAX(LENGTH(evento))
FROM TB_TEAMS;

SELECT * FROM TB_ATLETAS WHERE ID = 154;



DROP TABLE TB_ATLETAS;

ALTER TABLE TB_ATLETAS RENAME TO TB_ATHLETES;
ALTER TABLE TB_TECNICOS RENAME TO TB_COACHES;
ALTER TABLE TB_TECNICOS MODIFY nome VARCHAR(80);

SELECT id, nome, 
CASE WHEN pais = 'Brazil' THEN 'BRASIL'
ELSE pais
END AS PAIS FROM TB_TECNICOS;

show variables like '%char%';
show variables like '%coll%';

ALTER DATABASE TOKYO_2021 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
ALTER DATABASE TOKYO_2021 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_la_0900_ai_ci;

ALTER TABLE TB_TECNICOS CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_la_0900_ai_ci;








SELECT * FROM TB_ATLETAS WHERE pais LIKE 'Brazil' LIMIT 50;
SELECT COUNT(*) FROM TB_ATLETAS WHERE pais LIKE 'BRAZIL';




select * from tb_coaches;
select * from tb_athletes limit 100;
select * from tb_entries_gender;
select * from tb_medals;
select * from tb_teams;









/*
-- SELECT UPPER(nome) FROM TB_ATLETAS LIMIT 5;
-- SELECT FIND_IN_SET(" ", nome) from tb_atletas;
SELECT nome FROM TB_ATLETAS
WHERE nome REGEXP '^[A-Z]';
SELECT SUBSTRING_INDEX(nome, " ", 1) FROM TB_ATLETAS LIMIT 5; -- Pega o sobrenome em maiúsculas
SELECT POSITION(" " IN nome) FROM TB_ATLETAS LIMIT 10; -- Pega a posição do primeiro espaço
SELECT SUBSTRING_INDEX(nome, " ", 1) FROM TB_ATLETAS LIMIT 5;
SELECT SUBSTRING_INDEX(nome, SUBSTRING_INDEX(nome, " ", 1), -1) FROM TB_ATLETAS WHERE id = 5682;
SELECT LEFT(nome, LENGTH(SUBSTRING_INDEX(nome, " ", 1))) FROM TB_ATLETAS; -- Pega o sobrenome em maiúsculas
SELECT RIGHT(nome, (LENGTH(nome) - LENGTH(SUBSTRING_INDEX(nome, " ", 1)))) FROM TB_ATLETAS;

SELECT RIGHT (SUBSTRING_INDEX(nome, " ", SUBSTRING_INDEX(nome, " ", 1)) AS NOME FROM TB_ATLETAS LIMIT 5;
SELECT LEFT (SUBSTRING_INDEX(nome, " ", POSITION(" " IN nome)), POSITION(" " IN nome)) AS NOME FROM TB_ATLETAS LIMIT 5;


SELECT LEFT(SUBSTRING_INDEX(endereco, 'BR-', -1), 8) AS CEP
FROM enderecos
WHERE endereco REGEXP 'BR-[0-9]{8}'
*/