CREATE DATABASE TOKYO_2021 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE TOKYO_2021;

CREATE TABLE TB_ATLETAS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 11085
nome VARCHAR(100), -- 35
pais VARCHAR(60), -- 34
disciplina VARCHAR(60) -- 21
);

CREATE TABLE TB_TECNICOS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 394
nome VARCHAR(100), -- 30
pais VARCHAR(60), -- 26
disciplina VARCHAR(60), -- 17
evento VARCHAR(25) -- 8
);

CREATE TABLE TB_ENTRIES_GENDER(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 46
disciplina VARCHAR(60), -- 21
female SMALLINT,
male SMALLINT,
total SMALLINT
);

CREATE TABLE TB_MEDALS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ranking TINYINT,
team VARCHAR(80), -- 26
gold SMALLINT,
silver SMALLINT,
bronze SMALLINT,
total SMALLINT,
ranking_by_total TINYINT
);

CREATE TABLE TB_TEAMS(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, -- 743
nome VARCHAR(80), -- 34
disciplina VARCHAR(60), -- 19
noc VARCHAR(80), -- 26
evento VARCHAR(60) -- 32
);